// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tblvootpuymihoaeupak.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRibHZvb3RwdXltaWhvYWV1cGFrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzAxMDExMTEsImV4cCI6MjA0NTY3NzExMX0.x-1mkwbjJbOQ8ZBtVc4xxXOmNpakZTpZatuWSpdp9Hs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);